language: go
go:
  - 1.11.x
env:
  - GO111MODULE=on 
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - GOOS=windows go install -mod vendor github.com/liujianping/ts
  - GOOS=linux go install -mod vendor github.com/liujianping/ts
  - GOOS=darwin go install -mod vendor github.com/liujianping/ts
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux